# config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: climate_report
    document_managers:
        default:
            auto_mapping: true
